# Минимальный, расширим позже по мере необходимости
US: "United States"
CA: "Canada"
GB: "United Kingdom"
NL: "Netherlands"
DE: "Germany"
FR: "France"
ES: "Spain"
IT: "Italy"
RU: "Russia"
CN: "China"
JP: "Japan"
IN: "India"
AU: "Australia"
BR: "Brazil"
MX: "Mexico"
PL: "Poland"
PT: "Portugal"
BE: "Belgium"
AT: "Austria"
SE: "Sweden"
NO: "Norway"
DK: "Denmark"
FI: "Finland"
IE: "Ireland"
CH: "Switzerland"
