latin:
  street: ["st", "st.", "str", "street"]
  avenue: ["ave", "av", "av.", "avenue"]
  boulevard: ["blvd", "blvd.", "boulevard"]
  road: ["rd", "rd.", "road"]
  lane: ["ln", "ln.", "lane"]
  drive: ["dr", "dr.", "drive"]
  court: ["ct", "ct.", "court"]
  place: ["pl", "pl.", "place"]
  square: ["sq", "sq.", "square"]
  highway: ["hwy", "hwy.", "highway"]
  parkway: ["pkwy", "pkwy.", "parkway"]
  circle: ["cir", "cir.", "circle"]
  way: ["way"]
  terrace: ["ter", "ter.", "terrace"]
  trail: ["trl", "trl.", "trail"]

cyrillic:
  улица: ["ул", "ул.", "улица"]
  проспект: ["просп", "пр-т", "пр-т.", "проспект"]
  проезд: ["пр-д", "проезд"]
  переулок: ["пер", "пер.", "переулок"]
  бульвар: ["бул", "бульв", "бульвар"]
  шоссе: ["ш", "ш.", "шоссе"]
  набережная: ["наб", "наб.", "набережная"]
  площадь: ["пл", "пл.", "площадь"]
  тракт: ["тракт"]
